### ISSUE TITLE
Any update to fix the loading node

### ISSUE THREAD

**Issue by S0LTIS** [Julian-adv/WildDivide#1]
![image](https://github.com/user-attachments/assets/95927749-cd2a-4ec7-9c11-9e12105db08d)

**Comment by Julian-adv** [comment]
I think I fixed it. Please try updated version.

**Comment by S0LTIS** [comment]
> I think I fixed it. Please try updated version.

Ok thank you. Any idea why my wildcards are not loading for your node? I checked the directory and there's no folder called "Wildcards" like there is for the Impact Nodes. Any assistance will be greatly appreciated.

**Comment by S0LTIS** [comment]
> @S0LTIS
> 
> Can you please share what you had to do to get it working, so the rest of us can benefit from your solution?
> 
> Thank you 🙇‍♂️🙏

I made a "wildcards" folder in the node's directory.
![image](https://github.com/user-attachments/assets/59e79c15-9f11-4b74-8f6d-f23d6d5bb3a0)
